"""
action_schema.py

This file defines the schema for actions generated by the AI planner.

Its purpose is to:
- Validate AI-generated actions
- Enforce allowed action types
- Prevent unsafe or malformed instructions from executing
"""

from typing import Optional, List
from pydantic import BaseModel, Field, validator


class Action(BaseModel):
    """
    Action represents a single step that the agent wants to perform.

    IMPORTANT:
    - This is ONLY a data structure
    - No logic or execution is allowed here
    """

    # The type of action to perform
    action: str = Field(
        ...,
        description="Type of action to perform (must be from allowed list)"
    )

    # Source path (used for move/rename actions)
    source: Optional[str] = Field(
        None,
        description="Source file or folder path"
    )

    # Destination path (used for move/create actions)
    destination: Optional[str] = Field(
        None,
        description="Destination file or folder path"
    )

    # Reason provided by the AI for transparency
    reason: str = Field(
        ...,
        description="Explanation of why this action is needed"
    )

    @validator("action")
    def validate_action_type(cls, value: str) -> str:
        """
        Ensure that the action is one of the allowed types.

        This prevents the LLM from inventing new or unsafe actions.
        """
        allowed_actions = {
            "create_folder",
            "move_file",
            "rename_file",
            "no_action"
        }

        if value not in allowed_actions:
            raise ValueError(
                f"Invalid action '{value}'. Allowed actions: {allowed_actions}"
            )

        return value


class Plan(BaseModel):
    """
    Plan represents the full response from the AI planner.

    It contains:
    - A short summary of intent
    - A list of validated actions
    """

    plan_summary: str = Field(
        ...,
        description="Short summary of what the agent intends to do"
    )

    actions: List[Action] = Field(
        ...,
        description="List of actions to execute"
    )
